import bcrypt from "bcryptjs";
import crypto from "crypto";
import { prisma } from "../prisma";
import { signToken } from "../lib/jwt";

export async function register(email: string, password: string, displayName?: string) {
  const existing = await prisma.user.findUnique({ where: { email } });
  if (existing) throw new Error("Email already registered");

  const passwordHash = await bcrypt.hash(password, 10);
  const user = await prisma.user.create({
    data: { email, passwordHash, displayName: displayName || email.split("@")[0] },
  });
  return { user, token: signToken({ userId: user.id, role: user.role }) };
}

export async function login(email: string, password: string) {
  const user = await prisma.user.findUnique({ where: { email } });
  if (!user || !user.passwordHash) throw new Error("Invalid email or password");
  const ok = await bcrypt.compare(password, user.passwordHash);
  if (!ok) throw new Error("Invalid email or password");
  return { user, token: signToken({ userId: user.id, role: user.role }) };
}

// Called by the Telegram bot on /start. Creates a wallet-holding user keyed by
// telegramId if this chat has never been seen before.
export async function findOrCreateTelegramUser(telegramId: string, telegramUsername?: string, displayName?: string) {
  const existing = await prisma.user.findUnique({ where: { telegramId } });
  if (existing) return existing;
  return prisma.user.create({
    data: { telegramId, telegramUsername, displayName: displayName || telegramUsername || `user_${telegramId}` },
  });
}

export async function createLinkCode(telegramId: string, telegramUsername?: string) {
  const code = crypto.randomInt(100000, 999999).toString();
  const expiresAt = new Date(Date.now() + 10 * 60 * 1000);
  await prisma.linkCode.create({ data: { code, telegramId, telegramUsername, expiresAt } });
  return code;
}

// Links a Telegram chat to a web account using a code generated by the bot's
// /link command. If a telegram-only account already exists for that chat
// (created via findOrCreateTelegramUser), its balance/history are merged in
// and the duplicate row is removed so the customer ends up with one wallet.
export async function linkAccountWithCode(webUserId: string, code: string) {
  const linkCode = await prisma.linkCode.findUnique({ where: { code } });
  if (!linkCode || linkCode.used || linkCode.expiresAt < new Date()) {
    throw new Error("Invalid or expired code");
  }

  const telegramOnlyUser = await prisma.user.findUnique({ where: { telegramId: linkCode.telegramId } });

  await prisma.$transaction(async (tx) => {
    if (telegramOnlyUser && telegramOnlyUser.id !== webUserId) {
      await tx.deposit.updateMany({ where: { userId: telegramOnlyUser.id }, data: { userId: webUserId } });
      await tx.order.updateMany({ where: { userId: telegramOnlyUser.id }, data: { userId: webUserId } });
      await tx.user.update({
        where: { id: webUserId },
        data: { balanceVnd: { increment: telegramOnlyUser.balanceVnd } },
      });
      await tx.user.delete({ where: { id: telegramOnlyUser.id } });
    }
    await tx.user.update({
      where: { id: webUserId },
      data: { telegramId: linkCode.telegramId, telegramUsername: linkCode.telegramUsername },
    });
    await tx.linkCode.update({ where: { code }, data: { used: true } });
  });

  return prisma.user.findUniqueOrThrow({ where: { id: webUserId } });
}
